#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  24000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000


#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_NC
#define AUDIO_I2S_GPIO_WS   GPIO_NUM_3   // LRC/LRCLK -> pin 3
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_2   // BCLK -> pin 2
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_1   // ESP32 DOUT -> MAX98357A DIN (pin 1)
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_NC  // No MIC input for MAX98357A

#define AUDIO_CODEC_PA_PIN       GPIO_NUM_NC
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_NC
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_NC
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR

#define BUILTIN_LED_GPIO        GPIO_NUM_0
#define BOOT_BUTTON_GPIO        GPIO_NUM_NC

#define DISPLAY_SPI_GPIO_SCLK    GPIO_NUM_5 // SCL - SPI Clock
#define DISPLAY_SPI_GPIO_MOSI    GPIO_NUM_6 // SDA - SPI MOSI (Data)
#define DISPLAY_SPI_GPIO_RST     GPIO_NUM_7 // RES - Reset
#define DISPLAY_SPI_GPIO_DC      GPIO_NUM_8 // DC - Data/Command
#define DISPLAY_SPI_GPIO_CS      GPIO_NUM_10 // CS - Chip Select

#define DISPLAY_WIDTH   96
#define DISPLAY_HEIGHT  64
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y true

#endif // _BOARD_CONFIG_H_
